# -*- coding: utf-8 -*-
# default conf.py content generated by RTD

from recommonmark.parser import CommonMarkParser

extensions = []
templates_path = ['/home/docs/checkouts/readthedocs.org/readthedocs/templates/sphinx', 'templates', '_templates', '.templates']
source_suffix = ['.rst', '.md']		
source_parsers = {		
            '.md': CommonMarkParser,		
        }
master_doc = 'index'
project = u'docs.rovacc.ro'
copyright = u'2016'
version = 'latest'
release = 'latest'
exclude_patterns = ['_build']
pygments_style = 'sphinx'
htmlhelp_basename = 'docs-bgvacc'
html_theme = 'sphinx_rtd_theme'
file_insertion_enabled = False
latex_documents = [
  ('index', 'bgvacc-docs.tex', u'ROVACC/BGVACC Documentation',
   u'', 'manual'),
]

# custom theme overrides to fix tables
def setup(app):
   app.add_stylesheet("theme_overrides.css")
